version: "3"
services:
  frontend:
    build: .
    ports:
      - "3339:80"
    networks:
      - frontend-network
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: always

networks:
  frontend-network:
